### ISSUE TITLE
I keep getting this error when I run the main.py

### ISSUE THREAD

**Issue by maddy1096** [giacgiuliari/icarus-framework#2]
---------------------------------------------------------------------------------
Configuration number 0
LSN phase
LSN computing
LSN computed in 0.5838227272033691
Traceback (most recent call last):
  File "main.py", line 354, in <module>
    main()
  File "main.py", line 152, in main
    sim.compute_simulation()
  File "F:\icarus-framework-master\icarus_simulator\icarus_simulator.py", line 41, in compute_simulation
    phase_result = phase.execute_phase(input_values, phase_fname)
  File "F:\icarus-framework-master\icarus_simulator\phases\base_phase.py", line 91, in execute_phase
    result, fname, compression="bz2", set_default_extension=False
  File "C:\Users\Mudhurika\Anaconda3\envs\env\lib\site-packages\compress_pickle\compress_pickle.py", line 101, in dump
    **kwargs,
  File "C:\Users\Mudhurika\Anaconda3\envs\env\lib\site-packages\compress_pickle\utils.py", line 121, in instantiate_compresser
    _path if isinstance(path, PATH_TYPES) else path, mode=mode, **kwargs
  File "C:\Users\Mudhurika\Anaconda3\envs\env\lib\site-packages\compress_pickle\compressers\bz2.py", line 30, in __init__
    self._stream = bz2.open(path, mode=mode, **kwargs)
  File "C:\Users\Mudhurika\Anaconda3\envs\env\lib\bz2.py", line 322, in open
    binary_file = BZ2File(filename, bz_mode, compresslevel=compresslevel)
  File "C:\Users\Mudhurika\Anaconda3\envs\env\lib\bz2.py", line 96, in __init__
    self._fp = _builtin_open(filename, mode)
OSError: [Errno 22] Invalid argument: 'result_dumps/LSN||LSN(reg-53°22x72f11e550km00h02m17s0000ms20200101000000-).pkl.bz2'

**Comment by maddy1096** [comment]
Can you please help me with this ??

**Comment by Ex-Origin** [comment]
There is no `result_dumps/` folder, you must first create one by `mkdir result_dumps/`.

**Comment by miaomiao1miao1** [comment]
Filenames shouldn't have '||' in Windows, so I replace '||' with '_' to fix this bug.

**Comment by DaoSHI3** [comment]
Help, Help, Help! Is the problem solved?

**Comment by DaoSHI3** [comment]
> Filenames shouldn't have '||' in Windows, so I replace '||' with '_' to fix this bug.

I can't find the corresponding file in the project.
