### ISSUE TITLE
Error after the Computation finished in main.py

### ISSUE THREAD

**Issue by debiantini** [giacgiuliari/icarus-framework#6]
I get the following error when trying to run the installation test:

---------------------------------------------------------------------------------
Configuration number 0
LSN phase
LSN reading
LSN read in 0.01568007469177246
LSN finished in 0.015705347061157227

Grid phase
Grid reading
Grid read in 0.0052869319915771484
Grid finished in 0.00534820556640625

Cover phase
Cover reading
Cover read in 0.056610107421875
Cover finished in 0.05664706230163574

Routes phase
Routes reading
Routes read in 6.425617456436157
Routes finished in 6.52467942237854

Edges phase
Edges reading
Edges read in 3.7677576541900635
Edges finished in 3.7678020000457764

Bw phase
Bw reading
Bw read in 0.02426314353942871
Bw finished in 0.025037765502929688

LAtk phase
LAtk reading
LAtk read in 0.00013327598571777344
LAtk finished in 0.0001461505889892578

ZAtk phase
ZAtk reading
ZAtk read in 6.580352783203125e-05
ZAtk finished in 8.273124694824219e-05

Computation finished
Traceback (most recent call last):
  File "/usr/local/icarus-framework/main.py", line 354, in <module>
    main()
  File "/usr/local/icarus-framework/main.py", line 245, in main
    b_ed = min(
ValueError: min() arg is an empty sequence

**Comment by SomeThingH** [comment]
hi, sir, did u figure it out ? i meet the same error .But i cant figure it out now

**Comment by yumomomomi** [comment]
Sir, I want to ask you in "pipenv install" did not encounter "RuntimeError: Failed to lock Pipfile.lock! The question of"，How can we solve this problem？

**Comment by Kaimar666** [comment]
这是一封自动回复邮件。已经收到您的来信。

**Comment by SomeThingH** [comment]
我是旭辉，信件已经收到。
